# Generated by Django 4.2.13 on 2024-07-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='total_amount',
            new_name='sale_price',
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity_sold',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
