# Generated by Django 4.2.13 on 2024-07-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_recentactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentactivity',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recentactivity',
            name='item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recentactivity',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
