# Generated by Django 4.2.13 on 2024-07-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_recentactivity_amount_recentactivity_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentActivity',
        ),
    ]
