# Generated by Django 4.2.13 on 2024-07-23 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_inventory_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
