# Generated by Django 4.2.13 on 2024-07-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_inventoryitem_last_modified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='last_modified_at',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='last_modified_by',
        ),
    ]
